# Generated by Django 6.0.2 on 2026-02-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teacher_mobile_number_alter_teacher_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='fcm_token',
        ),
    ]
